package server

import (
"fmt"
"net/http"
"strings"
)

func taskGraphsPlaceholderHandler(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/graphs/tasks" {
		http.NotFound(w, r)
		return
	}

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	var b strings.Builder
	b.WriteString(subPageHead("Task DAG"))
	b.WriteString("<style>")
	b.WriteString("*{box-sizing:border-box;}")
	b.WriteString(".legend{display:flex;gap:12px;flex-wrap:wrap;font-size:11px;margin-bottom:12px;}")
	b.WriteString(".legend-item{display:flex;align-items:center;gap:4px;}")
	b.WriteString(".legend-dot{width:10px;height:10px;border-radius:50%;}")
	b.WriteString(".graph-canvas{position:relative;min-height:400px;background:#1e1e1e;border:1px solid #3c3c3c;border-radius:8px;overflow:auto;}")
	b.WriteString("svg.dag{width:100%;height:100%;position:absolute;top:0;left:0;pointer-events:none;}")
	b.WriteString("svg.dag line{stroke-width:1.5;}")
	b.WriteString("svg.dag polygon{}")
	b.WriteString(".node{position:absolute;background:#252526;border:2px solid #3c3c3c;border-radius:8px;padding:8px 10px;font-size:11px;cursor:pointer;min-width:120px;z-index:1;transition:box-shadow 0.15s;}")
	b.WriteString(".node:hover{box-shadow:0 0 0 2px #0078d4;z-index:10;}")
	b.WriteString(".node .node-id{font-weight:700;color:#0078d4;margin-bottom:2px;}")
	b.WriteString(".node .node-title{color:#ccc;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:160px;}")
	b.WriteString(".node .node-status{font-size:10px;margin-top:3px;font-weight:600;text-transform:uppercase;}")
	b.WriteString(".node.s-PENDING{border-color:#858585;} .node.s-PENDING .node-status{color:#858585;}")
	b.WriteString(".node.s-READY{border-color:#3794ff;} .node.s-READY .node-status{color:#3794ff;}")
	b.WriteString(".node.s-IN_PROGRESS{border-color:#0078d4;} .node.s-IN_PROGRESS .node-status{color:#0078d4;}")
	b.WriteString(".node.s-BLOCKED{border-color:#f14c4c;} .node.s-BLOCKED .node-status{color:#f14c4c;}")
	b.WriteString(".node.s-DONE,.node.s-SUCCEEDED{border-color:#89d185;} .node.s-DONE .node-status,.node.s-SUCCEEDED .node-status{color:#89d185;}")
	b.WriteString(".node.s-CANCELED{border-color:#858585;} .node.s-CANCELED .node-status{color:#858585;}")
	b.WriteString(".node.s-FAILED{border-color:#f14c4c;} .node.s-FAILED .node-status{color:#f14c4c;}")
	b.WriteString(".node.s-REVIEW{border-color:#cca700;} .node.s-REVIEW .node-status{color:#cca700;}")
	b.WriteString(".node.critical-path{box-shadow:0 0 0 3px #cca700;} .node.cycle-node{box-shadow:0 0 0 3px #f14c4c;} .node.parallel-node{box-shadow:0 0 0 3px #3794ff;}")
	b.WriteString(".analysis-bar{background:#252526;border:1px solid #3c3c3c;border-radius:8px;padding:10px 14px;margin-bottom:12px;font-size:12px;color:#858585;display:flex;gap:18px;flex-wrap:wrap;}")
	b.WriteString(".analysis-bar .ab-item{display:flex;align-items:center;gap:5px;} .analysis-bar .ab-dot{width:8px;height:8px;border-radius:50%;}")
	b.WriteString(".info-panel{display:none;position:fixed;top:80px;right:32px;width:280px;background:#252526;border:1px solid #3c3c3c;border-radius:10px;padding:14px;font-size:12px;z-index:100;box-shadow:0 8px 32px rgba(0,0,0,0.5);}")
	b.WriteString(".info-panel.open{display:block;}")
	b.WriteString(".info-panel h3{margin:0 0 8px;font-size:14px;color:#ccc;}")
	b.WriteString(".info-panel .close{position:absolute;top:8px;right:10px;cursor:pointer;color:#858585;font-size:16px;}")
	b.WriteString(".info-panel .row{display:flex;justify-content:space-between;padding:3px 0;border-bottom:1px solid #3c3c3c;}")
	b.WriteString(".info-panel .label{color:#858585;} .info-panel .value{color:#ccc;}")
	b.WriteString("</style>")
	b.WriteString("<div class=\"card\">")
	b.WriteString("<h1>Task DAG</h1>")
	b.WriteString("<p>Interactive dependency graph from <span class=\"muted\" id=\"graph-query\">/api/v2/projects/proj_default/graphs/tasks</span></p>")
	b.WriteString("<div class=\"meta\">")
	b.WriteString("<label class=\"field\">Project<input class=\"input\" id=\"graph-project\" value=\"proj_default\"></label>")
	b.WriteString("<label class=\"field\">Status<select class=\"select\" id=\"graph-status-filter\">")
	b.WriteString("<option value=\"\">All</option>")
	b.WriteString("<option value=\"PENDING\">PENDING</option><option value=\"READY\">READY</option>")
	b.WriteString("<option value=\"IN_PROGRESS\">IN_PROGRESS</option><option value=\"BLOCKED\">BLOCKED</option>")
	b.WriteString("<option value=\"DONE\">DONE</option><option value=\"CANCELED\">CANCELED</option>")
	b.WriteString("<option value=\"FAILED\">FAILED</option></select></label>")
	b.WriteString("<span id=\"graph-status\">Loading...</span>")
	b.WriteString("<button class=\"btn\" id=\"graph-refresh\" type=\"button\">Refresh</button></div>")
	b.WriteString("<div class=\"legend\">")
	b.WriteString("<span class=\"legend-item\"><span class=\"legend-dot\" style=\"background:#858585\"></span>Pending</span>")
	b.WriteString("<span class=\"legend-item\"><span class=\"legend-dot\" style=\"background:#3794ff\"></span>Ready</span>")
	b.WriteString("<span class=\"legend-item\"><span class=\"legend-dot\" style=\"background:#0078d4\"></span>In Progress</span>")
	b.WriteString("<span class=\"legend-item\"><span class=\"legend-dot\" style=\"background:#f14c4c\"></span>Blocked</span>")
	b.WriteString("<span class=\"legend-item\"><span class=\"legend-dot\" style=\"background:#89d185\"></span>Done</span>")
	b.WriteString("<span class=\"legend-item\"><span class=\"legend-dot\" style=\"background:#f14c4c\"></span>Failed</span>")
	b.WriteString("</div>")
	b.WriteString("<div class=\"graph-canvas\" id=\"graph-canvas\"><svg class=\"dag\" id=\"dag-svg\"></svg></div>")
	b.WriteString("</div>")
	b.WriteString("<div class=\"info-panel\" id=\"info-panel\"><span class=\"close\" id=\"info-close\">&times;</span>")
	b.WriteString("<h3 id=\"info-title\"></h3><div id=\"info-body\"></div></div>")
	b.WriteString("<script>")
	b.WriteString("const canvasEl=document.getElementById('graph-canvas');")
	b.WriteString("const svgEl=document.getElementById('dag-svg');")
	b.WriteString("const statusEl=document.getElementById('graph-status');")
	b.WriteString("const queryEl=document.getElementById('graph-query');")
	b.WriteString("const refreshBtn=document.getElementById('graph-refresh');")
	b.WriteString("const projectEl=document.getElementById('graph-project');")
	b.WriteString("const statusFilterEl=document.getElementById('graph-status-filter');")
	b.WriteString("const infoPanel=document.getElementById('info-panel');")
	b.WriteString("const infoTitle=document.getElementById('info-title');")
	b.WriteString("const infoBody=document.getElementById('info-body');")
	b.WriteString("const infoClose=document.getElementById('info-close');")
	b.WriteString("infoClose.addEventListener('click',()=>infoPanel.classList.remove('open'));")
	b.WriteString("const statusColors={PENDING:'#858585',READY:'#3794ff',IN_PROGRESS:'#0078d4',BLOCKED:'#f14c4c',DONE:'#89d185',SUCCEEDED:'#89d185',CANCELED:'#858585',FAILED:'#f14c4c',REVIEW:'#cca700'};")
	// Layout algorithm: Kahn's topological sort to assign layers, then position nodes
	b.WriteString("function layoutDAG(nodes,edges){")
	b.WriteString("const nodeMap=new Map();nodes.forEach(n=>nodeMap.set(String(n.id),n));")
	b.WriteString("const inDeg=new Map();const adj=new Map();")
	b.WriteString("nodes.forEach(n=>{const id=String(n.id);inDeg.set(id,0);adj.set(id,[]);});")
	b.WriteString("edges.forEach(e=>{const from=String(e.from);const to=String(e.to);")
	b.WriteString("if(adj.has(from)&&inDeg.has(to)){adj.get(from).push(to);inDeg.set(to,(inDeg.get(to)||0)+1);}});")
	// Kahn's algorithm for topological layers
	b.WriteString("const layers=[];const queue=[];")
	b.WriteString("inDeg.forEach((d,id)=>{if(d===0)queue.push(id);});")
	b.WriteString("const visited=new Set();")
	b.WriteString("while(queue.length>0){const layer=[...queue];queue.length=0;layers.push(layer);")
	b.WriteString("layer.forEach(id=>{visited.add(id);(adj.get(id)||[]).forEach(to=>{")
	b.WriteString("inDeg.set(to,(inDeg.get(to)||0)-1);if(inDeg.get(to)===0&&!visited.has(to))queue.push(to);});});}")
	// Handle nodes not in any layer (cycles or disconnected)
	b.WriteString("nodes.forEach(n=>{if(!visited.has(String(n.id))){")
	b.WriteString("if(layers.length===0)layers.push([]);layers[layers.length-1].push(String(n.id));}});")
	// Assign positions
	b.WriteString("const positions=new Map();const nodeW=140;const nodeH=70;const padX=40;const padY=30;")
	b.WriteString("const gapX=nodeW+padX;const gapY=nodeH+padY;")
	b.WriteString("let maxX=0;")
	b.WriteString("layers.forEach((layer,li)=>{layer.forEach((id,ni)=>{")
	b.WriteString("const x=ni*gapX+padX;const y=li*gapY+padY;")
	b.WriteString("positions.set(id,{x,y});if(x+nodeW>maxX)maxX=x+nodeW;});});")
	b.WriteString("const totalH=layers.length*gapY+padY;const totalW=maxX+padX;")
	b.WriteString("return {positions,totalW,totalH,nodeW,nodeH};}")

	// Critical path analysis: longest path in DAG using dynamic programming
	b.WriteString("function findCriticalPath(nodes,edges){")
	b.WriteString("const adj=new Map();const ids=new Set();")
	b.WriteString("nodes.forEach(n=>{const id=String(n.id);ids.add(id);adj.set(id,[]);});")
	b.WriteString("edges.forEach(e=>{const f=String(e.from);const t=String(e.to);if(adj.has(f))adj.get(f).push(t);});")
	b.WriteString("const dist=new Map();const prev=new Map();ids.forEach(id=>{dist.set(id,0);prev.set(id,null);});")
	b.WriteString("const visited=new Set();const order=[];")
	b.WriteString("function dfs(id){if(visited.has(id))return;visited.add(id);(adj.get(id)||[]).forEach(t=>dfs(t));order.push(id);}")
	b.WriteString("ids.forEach(id=>dfs(id));order.reverse();")
	b.WriteString("order.forEach(id=>{(adj.get(id)||[]).forEach(t=>{if(dist.get(id)+1>dist.get(t)){dist.set(t,dist.get(id)+1);prev.set(t,id);}});});")
	b.WriteString("let maxDist=0;let endNode=null;dist.forEach((d,id)=>{if(d>maxDist){maxDist=d;endNode=id;}});")
	b.WriteString("const path=[];let cur=endNode;while(cur!==null){path.unshift(cur);cur=prev.get(cur);}return {path,length:maxDist};}")

	// Cycle detection using DFS coloring
	b.WriteString("function detectCycles(nodes,edges){")
	b.WriteString("const adj=new Map();nodes.forEach(n=>adj.set(String(n.id),[]));")
	b.WriteString("edges.forEach(e=>{const f=String(e.from);if(adj.has(f))adj.get(f).push(String(e.to));});")
	b.WriteString("const white=new Set(nodes.map(n=>String(n.id)));const gray=new Set();const black=new Set();")
	b.WriteString("const cycles=[];")
	b.WriteString("function dfs(id,stack){white.delete(id);gray.add(id);stack.push(id);")
	b.WriteString("for(const t of (adj.get(id)||[])){if(gray.has(t)){const ci=stack.indexOf(t);if(ci>=0)cycles.push(stack.slice(ci));}")
	b.WriteString("else if(white.has(t))dfs(t,[...stack]);}gray.delete(id);black.add(id);}")
	b.WriteString("while(white.size>0){const id=white.values().next().value;dfs(id,[]);}return cycles;}")

	// Parallel execution: nodes at same topological layer with no dependencies between them
	b.WriteString("function findParallelGroups(nodes,edges){")
	b.WriteString("const inDeg=new Map();const adj=new Map();")
	b.WriteString("nodes.forEach(n=>{const id=String(n.id);inDeg.set(id,0);adj.set(id,[]);});")
	b.WriteString("edges.forEach(e=>{const f=String(e.from);const t=String(e.to);if(adj.has(f)&&inDeg.has(t)){adj.get(f).push(t);inDeg.set(t,(inDeg.get(t)||0)+1);}});")
	b.WriteString("const layers=[];const queue=[];const visited=new Set();")
	b.WriteString("inDeg.forEach((d,id)=>{if(d===0)queue.push(id);});")
	b.WriteString("while(queue.length>0){const layer=[...queue];queue.length=0;layers.push(layer);")
	b.WriteString("layer.forEach(id=>{visited.add(id);(adj.get(id)||[]).forEach(t=>{inDeg.set(t,(inDeg.get(t)||0)-1);if(inDeg.get(t)===0&&!visited.has(t))queue.push(t);});});}")
	b.WriteString("return layers.filter(l=>l.length>1);}")

	// Render function
	b.WriteString("function renderGraph(data){")
	b.WriteString("const nodes=data.nodes||[];const edges=data.edges||[];")
	b.WriteString("const statusFilter=statusFilterEl.value;")
	b.WriteString("const filteredNodes=statusFilter?nodes.filter(n=>(n.status||'').toUpperCase()===statusFilter):nodes;")
	b.WriteString("const filteredIds=new Set(filteredNodes.map(n=>String(n.id)));")
	b.WriteString("const filteredEdges=edges.filter(e=>filteredIds.has(String(e.from))&&filteredIds.has(String(e.to)));")
	// Run analysis
	b.WriteString("const cp=findCriticalPath(filteredNodes,filteredEdges);")
	b.WriteString("const cycles=detectCycles(filteredNodes,filteredEdges);")
	b.WriteString("const parallel=findParallelGroups(filteredNodes,filteredEdges);")
	b.WriteString("const cpSet=new Set(cp.path);")
	b.WriteString("const cycleNodes=new Set();cycles.forEach(c=>c.forEach(id=>cycleNodes.add(id)));")
	b.WriteString("const parallelNodes=new Set();parallel.forEach(g=>g.forEach(id=>parallelNodes.add(id)));")
	// Build analysis summary
	b.WriteString("let analysis='';")
	b.WriteString("if(cp.path.length>1)analysis+=' | Critical path: '+cp.path.length+' nodes (len '+cp.length+')';")
	b.WriteString("if(cycles.length>0)analysis+=' | \\u26A0 '+cycles.length+' cycle(s) detected!';")
	b.WriteString("if(parallel.length>0)analysis+=' | '+parallel.length+' parallel group(s)';")
	b.WriteString("statusEl.textContent=filteredNodes.length+' nodes, '+filteredEdges.length+' edges'+analysis;")
	b.WriteString("canvasEl.querySelectorAll('.node').forEach(el=>el.remove());")
	b.WriteString("svgEl.innerHTML='';")
	b.WriteString("if(filteredNodes.length===0){canvasEl.style.minHeight='100px';return;}")
	b.WriteString("const {positions,totalW,totalH,nodeW,nodeH}=layoutDAG(filteredNodes,filteredEdges);")
	b.WriteString("canvasEl.style.width=totalW+'px';canvasEl.style.height=totalH+'px';canvasEl.style.minHeight=totalH+'px';")
	b.WriteString("svgEl.setAttribute('width',totalW);svgEl.setAttribute('height',totalH);svgEl.setAttribute('viewBox','0 0 '+totalW+' '+totalH);")
	// Render analysis bar above the canvas
	b.WriteString("let oldBar=document.getElementById('analysis-bar');if(oldBar)oldBar.remove();")
	b.WriteString("if(cp.path.length>1||cycles.length>0||parallel.length>0){")
	b.WriteString("const bar=document.createElement('div');bar.id='analysis-bar';bar.className='analysis-bar';")
	b.WriteString("let barHtml='';")
	b.WriteString("if(cp.path.length>1)barHtml+='<span class=\"ab-item\"><span class=\"ab-dot\" style=\"background:#f59e0b\"></span>Critical Path: '+cp.path.length+' nodes</span>';")
	b.WriteString("if(cycles.length>0)barHtml+='<span class=\"ab-item\"><span class=\"ab-dot\" style=\"background:#ef4444\"></span>\\u26A0 '+cycles.length+' cycle(s)</span>';")
	b.WriteString("if(parallel.length>0)barHtml+='<span class=\"ab-item\"><span class=\"ab-dot\" style=\"background:#38bdf8\"></span>'+parallel.length+' parallel group(s)</span>';")
	b.WriteString("bar.innerHTML=barHtml;canvasEl.parentNode.insertBefore(bar,canvasEl);}")
	// Draw edges as SVG lines with arrowheads
	b.WriteString("const ns='http://www.w3.org/2000/svg';")
	b.WriteString("const defs=document.createElementNS(ns,'defs');")
	b.WriteString("const depMarker=document.createElementNS(ns,'marker');")
	b.WriteString("depMarker.setAttribute('id','arrow-dep');depMarker.setAttribute('viewBox','0 0 10 10');")
	b.WriteString("depMarker.setAttribute('refX','10');depMarker.setAttribute('refY','5');")
	b.WriteString("depMarker.setAttribute('markerWidth','6');depMarker.setAttribute('markerHeight','6');")
	b.WriteString("depMarker.setAttribute('orient','auto-start-reverse');")
	b.WriteString("const poly=document.createElementNS(ns,'path');poly.setAttribute('d','M 0 0 L 10 5 L 0 10 z');poly.setAttribute('fill','#0078d4');")
	b.WriteString("depMarker.appendChild(poly);defs.appendChild(depMarker);")
	b.WriteString("const pcMarker=document.createElementNS(ns,'marker');")
	b.WriteString("pcMarker.setAttribute('id','arrow-pc');pcMarker.setAttribute('viewBox','0 0 10 10');")
	b.WriteString("pcMarker.setAttribute('refX','10');pcMarker.setAttribute('refY','5');")
	b.WriteString("pcMarker.setAttribute('markerWidth','6');pcMarker.setAttribute('markerHeight','6');")
	b.WriteString("pcMarker.setAttribute('orient','auto-start-reverse');")
	b.WriteString("const poly2=document.createElementNS(ns,'path');poly2.setAttribute('d','M 0 0 L 10 5 L 0 10 z');poly2.setAttribute('fill','#3c3c3c');")
	b.WriteString("pcMarker.appendChild(poly2);defs.appendChild(pcMarker);")
	b.WriteString("svgEl.appendChild(defs);")
	b.WriteString("filteredEdges.forEach(e=>{const from=positions.get(String(e.from));const to=positions.get(String(e.to));if(!from||!to)return;")
	b.WriteString("const line=document.createElementNS(ns,'line');")
	b.WriteString("line.setAttribute('x1',from.x+nodeW/2);line.setAttribute('y1',from.y+nodeH);")
	b.WriteString("line.setAttribute('x2',to.x+nodeW/2);line.setAttribute('y2',to.y);")
	b.WriteString("const isDep=e.type==='depends_on';")
	b.WriteString("const isCpEdge=cpSet.has(String(e.from))&&cpSet.has(String(e.to));")
	b.WriteString("line.setAttribute('stroke',isCpEdge?'#cca700':isDep?'#0078d4':'#3c3c3c');")
	b.WriteString("line.setAttribute('stroke-width',isCpEdge?'3':'1.5');")
	b.WriteString("line.setAttribute('stroke-dasharray',isDep?'':'5,3');")
	b.WriteString("line.setAttribute('marker-end',isDep?'url(#arrow-dep)':'url(#arrow-pc)');")
	b.WriteString("svgEl.appendChild(line);});")
	// Draw nodes as positioned divs
	b.WriteString("filteredNodes.forEach(n=>{const pos=positions.get(String(n.id));if(!pos)return;")
	b.WriteString("const div=document.createElement('div');")
	b.WriteString("const st=(n.status||'PENDING').toUpperCase();")
	b.WriteString("const nid=String(n.id);")
	b.WriteString("let extraCls='';if(cpSet.has(nid))extraCls+=' critical-path';if(cycleNodes.has(nid))extraCls+=' cycle-node';if(parallelNodes.has(nid))extraCls+=' parallel-node';")
	b.WriteString("div.className='node s-'+st+extraCls;")
	b.WriteString("div.style.left=pos.x+'px';div.style.top=pos.y+'px';div.style.width=nodeW+'px';")
	b.WriteString("let badges='';if(cpSet.has(nid))badges+='<span style=\"color:#f59e0b;font-size:9px;\">\\u2B50 CP</span> ';")
	b.WriteString("if(cycleNodes.has(nid))badges+='<span style=\"color:#ef4444;font-size:9px;\">\\u26A0 CYCLE</span> ';")
	b.WriteString("if(parallelNodes.has(nid))badges+='<span style=\"color:#38bdf8;font-size:9px;\">\\u2693 PAR</span> ';")
	b.WriteString("div.innerHTML='<div class=\"node-id\">#'+escapeHtml(n.id)+'</div><div class=\"node-title\">'+escapeHtml(n.title||'')+'</div><div class=\"node-status\">'+badges+escapeHtml(st)+'</div>';")
	b.WriteString("div.addEventListener('click',()=>{infoTitle.textContent='Task #'+n.id;")
	b.WriteString("infoBody.innerHTML='';const fields={Status:st,Type:n.type||'-',Title:n.title||'-',Parent:n.parent_task_id||'-','Critical Path':cpSet.has(nid)?'Yes':'No','In Cycle':cycleNodes.has(nid)?'Yes':'No','Can Parallelize':parallelNodes.has(nid)?'Yes':'No'};")
	b.WriteString("Object.entries(fields).forEach(([k,v])=>{const row=document.createElement('div');row.className='row';")
	b.WriteString("row.innerHTML='<span class=\"label\">'+k+'</span><span class=\"value\">'+escapeHtml(v)+'</span>';infoBody.appendChild(row);});")
	b.WriteString("infoPanel.classList.add('open');});")
	b.WriteString("canvasEl.appendChild(div);});}")

	// Load data
	b.WriteString("let graphData=null;")
	b.WriteString("async function loadGraph(){statusEl.textContent='Loading...';try{")
	b.WriteString("const pid=String(projectEl.value||'proj_default').trim();")
	b.WriteString("const url='/api/v2/projects/'+encodeURIComponent(pid)+'/graphs/tasks';queryEl.textContent=url;")
	b.WriteString("const res=await fetch(url);if(!res.ok)throw new Error('http '+res.status);")
	b.WriteString("graphData=await res.json();renderGraph(graphData);")
	b.WriteString("}catch(err){statusEl.textContent='Failed to load graph';}}")
	b.WriteString("refreshBtn.addEventListener('click',loadGraph);")
	b.WriteString("projectEl.addEventListener('change',loadGraph);")
	b.WriteString("statusFilterEl.addEventListener('change',()=>{if(graphData)renderGraph(graphData);});")
	b.WriteString("loadGraph();")
	b.WriteString("</script>")
	b.WriteString(subPageFoot())
	fmt.Fprint(w, b.String())
}

