package server

import (
	"fmt"
	"html"
	"net/http"
	"strings"
)

func repoPlaceholderHandler(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/repo" {
		http.NotFound(w, r)
		return
	}

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	var b strings.Builder
	b.WriteString(subPageHead("Repo Panel"))
	b.WriteString("<style>")
	b.WriteString(".columns{display:grid;grid-template-columns:1fr 1fr;gap:16px;}")
	b.WriteString("@media(max-width:700px){.columns{grid-template-columns:1fr;}}")
	b.WriteString(".tree{list-style:none;padding:0;margin:0;font-size:12px;font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace;}")
	b.WriteString(".tree li{padding:4px 6px;border-bottom:1px solid #3c3c3c;display:flex;gap:6px;align-items:center;}")
	b.WriteString(".tree li:hover{background:#2a2d2e;}")
	b.WriteString(".tree .icon{width:14px;text-align:center;color:#858585;}")
	b.WriteString(".tree .dir{color:#0078d4;cursor:pointer;}")
	b.WriteString(".tree .file{color:#ccc;}")
	b.WriteString(".change-list{list-style:none;padding:0;margin:0;font-size:12px;}")
	b.WriteString(".change-list li{padding:6px 8px;border-bottom:1px solid #3c3c3c;display:flex;gap:10px;align-items:center;}")
	b.WriteString(".change-list .badge{display:inline-block;padding:1px 6px;border-radius:4px;font-size:10px;font-weight:600;text-transform:uppercase;}")
	b.WriteString(".badge.modified{background:#854d0e;color:#fef08a;}")
	b.WriteString(".badge.added{background:#166534;color:#bbf7d0;}")
	b.WriteString(".badge.deleted{background:#991b1b;color:#fecaca;}")
	b.WriteString("</style>")
	b.WriteString("<div class=\"card\">")
	b.WriteString("<h1>Repo Panel</h1>")
	b.WriteString("<div class=\"meta\">")
	b.WriteString("<label class=\"field\">Project ID<select class=\"input\" id=\"repo-project\"><option value=\"\">Loading projects...</option></select></label>")
	b.WriteString("<button class=\"btn\" id=\"repo-refresh\" type=\"button\">Refresh</button>")
	b.WriteString("<button class=\"btn\" id=\"repo-scan\" type=\"button\" style=\"background:#0078d4;border-color:#0078d4;color:#fff;\">Scan Repo</button>")
	b.WriteString("<span id=\"repo-status\" class=\"muted\">Loading...</span></div>")
	b.WriteString("<div class=\"columns\">")
	b.WriteString("<div><h2>File Tree</h2><ul class=\"tree\" id=\"repo-tree\"><li>Loading...</li></ul></div>")
	b.WriteString("<div><h2>Recent Changes</h2><ul class=\"change-list\" id=\"repo-changes\"><li>Loading...</li></ul></div>")
	b.WriteString("</div></div>")
	b.WriteString("<script>")
	b.WriteString("const treeEl=document.getElementById('repo-tree');")
	b.WriteString("const changesEl=document.getElementById('repo-changes');")
	b.WriteString("const statusEl=document.getElementById('repo-status');")
	b.WriteString("const refreshBtn=document.getElementById('repo-refresh');")
	b.WriteString("const projectEl=document.getElementById('repo-project');")
	b.WriteString("function getProjectID(){return String(projectEl.value||'proj_default').trim();}")
	b.WriteString("async function loadTree(){treeEl.innerHTML='<li>Loading tree...</li>';try{")
	b.WriteString("const res=await fetch('/api/v2/projects/'+encodeURIComponent(getProjectID())+'/tree');")
	b.WriteString("if(!res.ok)throw new Error('http '+res.status);")
	b.WriteString("const data=await res.json();const entries=Array.isArray(data.entries)?data.entries:[];")
	b.WriteString("if(entries.length===0){treeEl.innerHTML='<li class=\"muted\">No files scanned yet. Scan a directory to populate the repo tree.</li>';return;}")
	b.WriteString("treeEl.innerHTML='';entries.forEach((e)=>{")
	b.WriteString("const li=document.createElement('li');")
	b.WriteString("const isDir=e.is_dir||e.kind==='dir';")
	b.WriteString("const icon=isDir?'\\uD83D\\uDCC1':'\\uD83D\\uDCC4';")
	b.WriteString("const cls=isDir?'dir':'file';")
	b.WriteString("li.innerHTML='<span class=\"icon\">'+icon+'</span><span class=\"'+cls+'\">'+escapeHtml(e.name||e.path)+'</span>';")
	b.WriteString("treeEl.appendChild(li);});")
	b.WriteString("}catch(err){treeEl.innerHTML='<li class=\"muted\">Failed to load tree</li>';}}")
	b.WriteString("async function loadChanges(){changesEl.innerHTML='<li>Loading changes...</li>';try{")
	b.WriteString("const res=await fetch('/api/v2/projects/'+encodeURIComponent(getProjectID())+'/changes');")
	b.WriteString("if(!res.ok)throw new Error('http '+res.status);")
	b.WriteString("const data=await res.json();const changes=Array.isArray(data.changes)?data.changes:[];")
	b.WriteString("if(changes.length===0){changesEl.innerHTML='<li class=\"muted\">No recent changes</li>';return;}")
	b.WriteString("changesEl.innerHTML='';changes.forEach((c)=>{")
	b.WriteString("const li=document.createElement('li');")
	b.WriteString("const kind=(c.kind||c.status||'modified').toLowerCase();")
	b.WriteString("const badgeCls=kind==='added'?'added':kind==='deleted'?'deleted':'modified';")
	b.WriteString("li.innerHTML='<span class=\"badge '+badgeCls+'\">'+escapeHtml(kind)+'</span><span>'+escapeHtml(c.path||c.name)+'</span>';")
	b.WriteString("changesEl.appendChild(li);});")
	b.WriteString("}catch(err){changesEl.innerHTML='<li class=\"muted\">Failed to load changes</li>';}}")
	b.WriteString("async function loadAll(){statusEl.textContent='Loading...';")
	b.WriteString("await Promise.all([loadTree(),loadChanges()]);statusEl.textContent='Loaded';}")
	b.WriteString("refreshBtn.addEventListener('click',loadAll);")
	b.WriteString("projectEl.addEventListener('change',loadAll);")
	// Scan button
	b.WriteString("document.getElementById('repo-scan').addEventListener('click',async()=>{statusEl.textContent='Scanning...';try{")
	b.WriteString("const res=await fetch('/api/v2/projects/'+encodeURIComponent(getProjectID())+'/files/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({purge:true})});")
	b.WriteString("if(!res.ok)throw new Error('http '+res.status);const data=await res.json();")
	b.WriteString("statusEl.textContent='Scan complete: '+data.synced+' synced, '+data.total+' total ('+data.scan_duration_ms+'ms)';")
	b.WriteString("loadAll();}catch(err){statusEl.textContent='Scan failed';}});")
	b.WriteString("async function loadProjects(){try{")
	b.WriteString("const res=await fetch('/api/v2/projects');if(!res.ok)throw new Error('http '+res.status);")
	b.WriteString("const data=await res.json();const projects=Array.isArray(data.projects)?data.projects:[];")
	b.WriteString("projectEl.innerHTML='';")
	b.WriteString("if(projects.length===0){projectEl.innerHTML='<option value=\"proj_default\">proj_default</option>';")
	b.WriteString("}else{projects.forEach((p)=>{const o=document.createElement('option');o.value=p.id;")
	b.WriteString("o.textContent=p.name?p.id+' — '+p.name:p.id;projectEl.appendChild(o);});}")
	b.WriteString("}catch(e){projectEl.innerHTML='<option value=\"proj_default\">proj_default</option>';}")
	b.WriteString("loadAll();}")
	b.WriteString("loadProjects();")
	b.WriteString("</script>")
	b.WriteString(subPageFoot())
	fmt.Fprint(w, b.String())
}


func repoGraphHandler(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/graphs/repo" {
		http.NotFound(w, r)
		return
	}

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	var b strings.Builder
	b.WriteString(subPageHead("Repo Graph"))
	b.WriteString("<style>")
	b.WriteString(".graph-canvas{position:relative;min-height:400px;background:#1e1e1e;border:1px solid #3c3c3c;border-radius:8px;overflow:auto;}")
	b.WriteString("svg.repo-dag{width:100%;height:100%;position:absolute;top:0;left:0;pointer-events:none;}")
	b.WriteString("svg.repo-dag line{stroke:#505050;stroke-width:1;}")
	b.WriteString(".rnode{position:absolute;background:#252526;border:1px solid #505050;border-radius:6px;padding:6px 8px;font-size:10px;z-index:1;cursor:pointer;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;}")
	b.WriteString(".rnode:hover{box-shadow:0 0 0 2px #0078d4;z-index:10;}")
	b.WriteString(".rnode.dir{border-color:#0078d4;color:#0078d4;}")
	b.WriteString(".rnode.file{border-color:#858585;color:#ccc;}")
	b.WriteString(".stats-row{display:flex;gap:16px;margin:12px 0;font-size:12px;}")
	b.WriteString(".stats-row .stat{color:#858585;}")
	b.WriteString(".stats-row .stat strong{color:#ccc;}")
	b.WriteString("</style>")
	b.WriteString("<div class=\"card\">")
	b.WriteString("<h1>Repo Entity Graph</h1>")
	b.WriteString("<p>File and directory relationships from project repo files</p>")
	b.WriteString("<div class=\"meta\">")
	b.WriteString("<label class=\"field\">Project<input class=\"input\" id=\"rg-project\" value=\"proj_default\"></label>")
	b.WriteString("<button class=\"btn\" id=\"rg-refresh\">Refresh</button>")
	b.WriteString("<span id=\"rg-status\" class=\"muted\">Loading...</span></div>")
	b.WriteString("<div class=\"stats-row\" id=\"rg-stats\"></div>")
	b.WriteString("<div class=\"graph-canvas\" id=\"rg-canvas\"><svg class=\"repo-dag\" id=\"rg-svg\"></svg></div>")
	b.WriteString("</div>")
	b.WriteString("<script>")
	b.WriteString("const canvasEl=document.getElementById('rg-canvas');")
	b.WriteString("const svgEl=document.getElementById('rg-svg');")
	b.WriteString("const statusEl=document.getElementById('rg-status');")
	b.WriteString("const statsEl=document.getElementById('rg-stats');")
	b.WriteString("const projectEl=document.getElementById('rg-project');")
	b.WriteString("const refreshBtn=document.getElementById('rg-refresh');")
	b.WriteString("function buildTree(files){const root={name:'/',children:{},isDir:true};")
	b.WriteString("files.forEach(f=>{const parts=(f.path||f.name||'').split('/').filter(Boolean);")
	b.WriteString("let cur=root;parts.forEach((p,i)=>{if(!cur.children[p])cur.children[p]={name:p,children:{},isDir:i<parts.length-1};")
	b.WriteString("cur=cur.children[p];});cur.lang=f.language||'';cur.size=f.size||0;});return root;}")
	b.WriteString("function flatten(node,depth,nodes,edges,parentIdx){")
	b.WriteString("const idx=nodes.length;nodes.push({name:node.name,isDir:node.isDir,depth,lang:node.lang||'',size:node.size||0});")
	b.WriteString("if(parentIdx!==null)edges.push({from:parentIdx,to:idx});")
	b.WriteString("const kids=Object.values(node.children).sort((a,b)=>(b.isDir?1:0)-(a.isDir?1:0)||a.name.localeCompare(b.name));")
	b.WriteString("kids.forEach(c=>flatten(c,depth+1,nodes,edges,idx));}")
	b.WriteString("function renderRepoGraph(files){")
	b.WriteString("const tree=buildTree(files);const nodes=[];const edges=[];flatten(tree,0,nodes,edges,null);")
	b.WriteString("const dirs=nodes.filter(n=>n.isDir).length;const fileCount=nodes.length-dirs;")
	b.WriteString("const langs=new Set(nodes.filter(n=>n.lang).map(n=>n.lang));")
	b.WriteString("statsEl.innerHTML='<span class=\"stat\">Files: <strong>'+fileCount+'</strong></span>'")
	b.WriteString("+'<span class=\"stat\">Dirs: <strong>'+dirs+'</strong></span>'")
	b.WriteString("+'<span class=\"stat\">Languages: <strong>'+langs.size+'</strong></span>';")
	b.WriteString("canvasEl.querySelectorAll('.rnode').forEach(el=>el.remove());svgEl.innerHTML='';")
	b.WriteString("const nodeW=120;const nodeH=28;const padX=20;const padY=8;const indentX=24;")
	b.WriteString("const positions=[];nodes.forEach((n,i)=>{const x=padX+n.depth*indentX;const y=padY+i*(nodeH+padY);positions.push({x,y});")
	b.WriteString("const div=document.createElement('div');div.className='rnode '+(n.isDir?'dir':'file');")
	b.WriteString("div.style.left=x+'px';div.style.top=y+'px';")
	b.WriteString("div.textContent=n.isDir?'\\uD83D\\uDCC1 '+n.name:n.name+(n.lang?' ('+n.lang+')':'');")
	b.WriteString("canvasEl.appendChild(div);});")
	b.WriteString("const totalH=nodes.length*(nodeH+padY)+padY;const totalW=Math.max(...positions.map(p=>p.x))+nodeW+padX*2;")
	b.WriteString("canvasEl.style.height=totalH+'px';canvasEl.style.width=totalW+'px';canvasEl.style.minHeight=totalH+'px';")
	b.WriteString("svgEl.setAttribute('width',totalW);svgEl.setAttribute('height',totalH);svgEl.setAttribute('viewBox','0 0 '+totalW+' '+totalH);")
	b.WriteString("const ns='http://www.w3.org/2000/svg';")
	b.WriteString("edges.forEach(e=>{const from=positions[e.from];const to=positions[e.to];if(!from||!to)return;")
	b.WriteString("const line=document.createElementNS(ns,'line');")
	b.WriteString("line.setAttribute('x1',from.x+6);line.setAttribute('y1',from.y+nodeH);")
	b.WriteString("line.setAttribute('x2',to.x+6);line.setAttribute('y2',to.y);svgEl.appendChild(line);});}")
	b.WriteString("async function loadRepoGraph(){statusEl.textContent='Loading...';try{")
	b.WriteString("const pid=String(projectEl.value||'proj_default').trim();")
	b.WriteString("const res=await fetch('/api/v2/projects/'+encodeURIComponent(pid)+'/files?limit=500');")
	b.WriteString("if(!res.ok)throw new Error('http '+res.status);")
	b.WriteString("const data=await res.json();const files=Array.isArray(data.files)?data.files:[];")
	b.WriteString("statusEl.textContent=files.length+' files';renderRepoGraph(files);")
	b.WriteString("}catch(err){statusEl.textContent='Failed to load repo files';}}")
	b.WriteString("refreshBtn.addEventListener('click',loadRepoGraph);")
	b.WriteString("projectEl.addEventListener('change',loadRepoGraph);")
	b.WriteString("loadRepoGraph();")
	b.WriteString("</script>")
	b.WriteString(subPageFoot())
	fmt.Fprint(w, b.String())
}

func diffViewerHandler(w http.ResponseWriter, r *http.Request) {
	trimmed := strings.TrimPrefix(r.URL.Path, "/diffs/")
	if trimmed == "" || trimmed == "/" || strings.Contains(trimmed, "/") {
		http.NotFound(w, r)
		return
	}

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	var b strings.Builder
	b.WriteString(subPageHead("Diff Viewer"))
	b.WriteString("<style>")
	b.WriteString(".diff-container{font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace;font-size:12px;line-height:1.6;overflow-x:auto;}")
	b.WriteString(".diff-line{display:flex;white-space:pre;}")
	b.WriteString(".diff-line .ln{min-width:40px;text-align:right;padding:0 8px;color:#858585;user-select:none;cursor:pointer;}")
	b.WriteString(".diff-line .ln:hover{background:#3c3c3c;color:#0078d4;}")
	b.WriteString(".diff-line .content{flex:1;padding:0 8px;}")
	b.WriteString(".diff-add{background:rgba(22,163,74,0.15);}")
	b.WriteString(".diff-add .content{color:#89d185;}")
	b.WriteString(".diff-del{background:rgba(220,38,38,0.15);}")
	b.WriteString(".diff-del .content{color:#f14c4c;}")
	b.WriteString(".diff-hunk{background:rgba(0,120,212,0.1);color:#0078d4;font-style:italic;}")
	b.WriteString(".diff-ctx .content{color:#858585;}")
	b.WriteString(".split{display:grid;grid-template-columns:1fr 1fr;gap:0;}")
	b.WriteString(".split .pane{overflow-x:auto;border:1px solid #3c3c3c;}")
	b.WriteString(".split .pane:first-child{border-right:none;}")
	b.WriteString(".file-list{list-style:none;padding:0;margin:0 0 12px;display:flex;flex-wrap:wrap;gap:6px;font-size:11px;}")
	b.WriteString(".file-list li{background:#1e1e1e;border:1px solid #3c3c3c;border-radius:6px;padding:3px 8px;cursor:pointer;}")
	b.WriteString(".file-list li:hover{background:#3c3c3c;}")
	b.WriteString(".comment-row{background:#252526;border-left:3px solid #0078d4;padding:6px 12px;margin:2px 0;font-size:12px;}")
	b.WriteString(".comment-row .cm-author{color:#0078d4;font-weight:600;margin-right:6px;} .comment-row .cm-body{color:#ccc;} .comment-row .cm-time{color:#858585;font-size:10px;margin-left:8px;}")
	b.WriteString(".comment-form{display:flex;gap:6px;padding:4px 12px;background:#252526;border-left:3px solid #505050;margin:2px 0;}")
	b.WriteString(".comment-form input{flex:1;background:#3c3c3c;border:1px solid #505050;border-radius:4px;color:#ccc;padding:4px 8px;font-size:12px;}")
	b.WriteString(".comment-form button{background:#505050;border:1px solid #606060;color:#ccc;border-radius:4px;padding:4px 10px;cursor:pointer;font-size:11px;}")
	b.WriteString("</style>")
	b.WriteString("<div class=\"card\">")
	b.WriteString("<h1>Diff Viewer</h1>")
	b.WriteString("<p>Artifact: <span class=\"muted\" id=\"diff-artifact-id\"></span></p>")
	b.WriteString("<div class=\"meta\">")
	b.WriteString("<button class=\"btn active\" id=\"btn-unified\" type=\"button\">Unified</button>")
	b.WriteString("<button class=\"btn\" id=\"btn-split\" type=\"button\">Split</button>")
	b.WriteString("<span id=\"diff-status\" class=\"muted\">Loading...</span></div>")
	b.WriteString("<ul class=\"file-list\" id=\"diff-files\"></ul>")
	b.WriteString("<div class=\"diff-container\" id=\"diff-content\">Loading...</div>")
	b.WriteString("</div>")
	b.WriteString("<script>")
	b.WriteString("const artifactId='" + html.EscapeString(trimmed) + "';")
	b.WriteString("document.getElementById('diff-artifact-id').textContent=artifactId;")
	b.WriteString("const contentEl=document.getElementById('diff-content');")
	b.WriteString("const statusEl=document.getElementById('diff-status');")
	b.WriteString("const filesEl=document.getElementById('diff-files');")
	b.WriteString("const btnUnified=document.getElementById('btn-unified');")
	b.WriteString("const btnSplit=document.getElementById('btn-split');")
	b.WriteString("let diffText='';let viewMode='unified';")
	b.WriteString("function parseDiffFiles(text){const files=[];const re=/^diff --git a\\/(.+?) b\\//gm;let m;while((m=re.exec(text))!==null)files.push(m[1]);")
	b.WriteString("if(files.length===0){const hdr=/^--- a\\/(.+)$/gm;while((m=hdr.exec(text))!==null)files.push(m[1]);}return files;}")
	b.WriteString("function renderUnified(text){const lines=text.split('\\n');let html='';let ln=0;")
	b.WriteString("lines.forEach((line)=>{ln++;let cls='diff-ctx';")
	b.WriteString("if(line.startsWith('+')){cls='diff-add';}else if(line.startsWith('-')){cls='diff-del';}else if(line.startsWith('@@')){cls='diff-hunk';}")
	b.WriteString("html+='<div class=\"diff-line '+cls+'\"><span class=\"ln\">'+ln+'</span><span class=\"content\">'+escapeHtml(line)+'</span></div>';});")
	b.WriteString("return html;}")
	b.WriteString("function renderSplit(text){const lines=text.split('\\n');let left='';let right='';let lln=0;let rln=0;")
	b.WriteString("lines.forEach((line)=>{")
	b.WriteString("if(line.startsWith('-')){lln++;left+='<div class=\"diff-line diff-del\"><span class=\"ln\">'+lln+'</span><span class=\"content\">'+escapeHtml(line.slice(1))+'</span></div>';")
	b.WriteString("right+='<div class=\"diff-line\"><span class=\"ln\"></span><span class=\"content\"></span></div>';}")
	b.WriteString("else if(line.startsWith('+')){rln++;right+='<div class=\"diff-line diff-add\"><span class=\"ln\">'+rln+'</span><span class=\"content\">'+escapeHtml(line.slice(1))+'</span></div>';")
	b.WriteString("left+='<div class=\"diff-line\"><span class=\"ln\"></span><span class=\"content\"></span></div>';}")
	b.WriteString("else if(line.startsWith('@@')){const h='<div class=\"diff-line diff-hunk\"><span class=\"ln\"></span><span class=\"content\">'+escapeHtml(line)+'</span></div>';left+=h;right+=h;}")
	b.WriteString("else{lln++;rln++;const row='<div class=\"diff-line diff-ctx\"><span class=\"ln\">'+(lln)+'</span><span class=\"content\">'+escapeHtml(line)+'</span></div>';left+=row;right+=row;}});")
	b.WriteString("return '<div class=\"split\"><div class=\"pane\">'+left+'</div><div class=\"pane\">'+right+'</div></div>';}")
	b.WriteString("function renderDiff(){if(!diffText){contentEl.innerHTML='<span class=\"muted\">No diff content</span>';return;}")
	b.WriteString("contentEl.innerHTML=viewMode==='split'?renderSplit(diffText):renderUnified(diffText);}")
	b.WriteString("async function loadDiff(){statusEl.textContent='Loading...';contentEl.innerHTML='Loading...';try{")
	b.WriteString("const res=await fetch('/api/v2/artifacts/'+encodeURIComponent(artifactId)+'/content');")
	b.WriteString("if(res.ok){diffText=await res.text();}else{")
	b.WriteString("const res2=await fetch('/api/v2/artifacts/'+encodeURIComponent(artifactId));")
	b.WriteString("if(!res2.ok)throw new Error('http '+res2.status);const data=await res2.json();diffText=data.content||data.body||JSON.stringify(data,null,2);}")
	b.WriteString("const files=parseDiffFiles(diffText);filesEl.innerHTML='';")
	b.WriteString("files.forEach((f)=>{const li=document.createElement('li');li.textContent=f;filesEl.appendChild(li);});")
	b.WriteString("statusEl.textContent=files.length+' file(s)';renderDiff();")
	b.WriteString("}catch(err){statusEl.textContent='Failed to load diff';contentEl.innerHTML='<span class=\"muted\">Could not load artifact</span>';}}")
	b.WriteString("btnUnified.addEventListener('click',()=>{viewMode='unified';btnUnified.classList.add('active');btnSplit.classList.remove('active');renderDiff();});")
	b.WriteString("btnSplit.addEventListener('click',()=>{viewMode='split';btnSplit.classList.add('active');btnUnified.classList.remove('active');renderDiff();});")
	// Line comment functionality
	b.WriteString("let comments=[];")
	b.WriteString("async function loadComments(){try{const res=await fetch('/api/v2/artifacts/'+encodeURIComponent(artifactId)+'/comments');if(res.ok){const data=await res.json();comments=data.comments||[];}}catch(e){}}")
	b.WriteString("async function postComment(lineNumber,body){try{const res=await fetch('/api/v2/artifacts/'+encodeURIComponent(artifactId)+'/comments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({line_number:lineNumber,body:body,author:'reviewer'})});if(res.ok){await loadComments();renderDiff();}}catch(e){}}")
	b.WriteString("function renderCommentsForLine(container,ln){const lc=comments.filter(c=>c.line_number===ln);lc.forEach(c=>{const div=document.createElement('div');div.className='comment-row';div.innerHTML='<span class=\"cm-author\">'+escapeHtml(c.author||'anon')+'</span><span class=\"cm-body\">'+escapeHtml(c.body)+'</span><span class=\"cm-time\">'+escapeHtml(c.created_at||'')+'</span>';container.appendChild(div);});}")
	b.WriteString("contentEl.addEventListener('click',(e)=>{const lnEl=e.target.closest('.ln');if(!lnEl)return;const ln=parseInt(lnEl.textContent,10);if(isNaN(ln))return;")
	b.WriteString("const existing=lnEl.parentElement.nextElementSibling;if(existing&&existing.classList.contains('comment-form')){existing.remove();return;}")
	b.WriteString("const form=document.createElement('div');form.className='comment-form';form.innerHTML='<input placeholder=\"Add comment...\" autofocus><button>Post</button>';")
	b.WriteString("lnEl.parentElement.after(form);const inp=form.querySelector('input');inp.focus();form.querySelector('button').addEventListener('click',()=>{const val=inp.value.trim();if(val)postComment(ln,val);});inp.addEventListener('keydown',(ev)=>{if(ev.key==='Enter'){const val=inp.value.trim();if(val)postComment(ln,val);}if(ev.key==='Escape')form.remove();});});")
	// Enhance renderDiff to include inline comments
	b.WriteString("const origRenderDiff=renderDiff;")
	b.WriteString("renderDiff=function(){origRenderDiff();document.querySelectorAll('.diff-line').forEach(el=>{const lnEl=el.querySelector('.ln');if(!lnEl)return;const ln=parseInt(lnEl.textContent,10);if(isNaN(ln))return;renderCommentsForLine(el.parentElement||contentEl,ln);});};")
	b.WriteString("loadComments().then(()=>{loadDiff();});")
	b.WriteString("</script>")
	b.WriteString(subPageFoot())
	fmt.Fprint(w, b.String())
}

