package server

import (
	"fmt"
	"html"
	"net/http"
	"strings"
)

func runViewerPage(runID string) string {
	var b strings.Builder
	b.WriteString(subPageHead("Run Viewer"))
	b.WriteString("<style>")
	b.WriteString(".pill.s-RUNNING{border-color:#0078d4;color:#0078d4;} .pill.s-SUCCEEDED{border-color:#89d185;color:#89d185;}")
	b.WriteString(".pill.s-FAILED{border-color:#f14c4c;color:#f14c4c;} .pill.s-PENDING{border-color:#858585;color:#858585;}")
	b.WriteString(".stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:10px;margin-bottom:14px;}")
	// Step timeline
	b.WriteString(".step-timeline{display:flex;flex-direction:column;gap:0;margin-bottom:14px;}")
	b.WriteString(".step-item{display:flex;gap:12px;padding:8px 0;border-left:2px solid #3c3c3c;margin-left:8px;padding-left:16px;position:relative;}")
	b.WriteString(".step-item::before{content:'';position:absolute;left:-5px;top:12px;width:8px;height:8px;border-radius:50%;background:#505050;}")
	b.WriteString(".step-item.s-completed::before{background:#89d185;} .step-item.s-running::before{background:#0078d4;} .step-item.s-failed::before{background:#f14c4c;}")
	b.WriteString(".step-info{flex:1;} .step-name{font-size:13px;font-weight:600;color:#ccc;} .step-meta{font-size:11px;color:#858585;margin-top:2px;}")
	b.WriteString(".step-dur{font-size:11px;color:#858585;white-space:nowrap;}")
	// Log console
	b.WriteString(".log-console{background:#1e1e1e;border:1px solid #3c3c3c;border-radius:8px;padding:0;margin-bottom:14px;max-height:350px;overflow:auto;font-family:monospace;font-size:12px;}")
	b.WriteString(".log-console .log-line{padding:2px 12px;border-bottom:1px solid #252526;white-space:pre-wrap;word-break:break-all;}")
	b.WriteString(".log-console .log-line:nth-child(odd){background:#1a1a1a;}")
	b.WriteString(".log-console .log-ts{color:#858585;margin-right:8px;} .log-console .log-lvl{font-weight:600;margin-right:6px;}")
	b.WriteString(".log-console .log-lvl.l-error{color:#f14c4c;} .log-console .log-lvl.l-warn{color:#cca700;} .log-console .log-lvl.l-info{color:#3794ff;}")
	b.WriteString(".log-console .log-msg{color:#ccc;}")
	// Artifacts
	b.WriteString(".artifact-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:10px;margin-bottom:14px;}")
	b.WriteString(".artifact-card{background:#1e1e1e;border:1px solid #3c3c3c;border-radius:8px;padding:10px 12px;}")
	b.WriteString(".artifact-card .art-name{font-size:13px;font-weight:600;color:#0078d4;margin-bottom:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}")
	b.WriteString(".artifact-card .art-meta{font-size:11px;color:#858585;}")
	b.WriteString(".artifact-card .art-link{display:inline-block;margin-top:6px;font-size:11px;color:#0078d4;text-decoration:none;}")
	b.WriteString(".artifact-card .art-link:hover{text-decoration:underline;}")
	// Tabs
	b.WriteString(".tabs{display:flex;gap:0;margin-bottom:14px;border-bottom:1px solid #3c3c3c;}")
	b.WriteString(".tab-btn{background:none;border:none;color:#858585;padding:8px 16px;cursor:pointer;font-size:13px;border-bottom:2px solid transparent;}")
	b.WriteString(".tab-btn.active{color:#0078d4;border-bottom-color:#0078d4;} .tab-btn:hover{color:#ccc;}")
	b.WriteString(".tab-content{display:none;} .tab-content.active{display:block;}")
	b.WriteString("pre{background:#1e1e1e;border:1px solid #3c3c3c;border-radius:8px;padding:12px;font-size:12px;overflow:auto;}")
	b.WriteString("</style>")
	b.WriteString("<div class=\"card\" data-run-id=\"")
	b.WriteString(html.EscapeString(runID))
	b.WriteString("\">")
	b.WriteString("<h1>Run Viewer</h1>")
	b.WriteString("<p>Run ID: ")
	b.WriteString(html.EscapeString(runID))
	b.WriteString("</p>")
	b.WriteString("<div class=\"meta\">")
	b.WriteString("<span class=\"pill\" id=\"run-status\">Loading...</span>")
	b.WriteString("<span class=\"muted\" id=\"run-timing\"></span>")
	b.WriteString("<span class=\"muted\">/api/v2/runs/")
	b.WriteString(html.EscapeString(runID))
	b.WriteString("</span>")
	b.WriteString("</div>")
	b.WriteString("<div class=\"stats\">")
	b.WriteString("<div class=\"stat\"><span>Steps</span><strong id=\"run-steps\">-</strong></div>")
	b.WriteString("<div class=\"stat\"><span>Artifacts</span><strong id=\"run-artifacts\">-</strong></div>")
	b.WriteString("<div class=\"stat\"><span>Logs</span><strong id=\"run-logs\">-</strong></div>")
	b.WriteString("<div class=\"stat\"><span>Tool Calls</span><strong id=\"run-tools\">-</strong></div>")
	b.WriteString("</div>")
	// Tabs
	b.WriteString("<div class=\"tabs\">")
	b.WriteString("<button class=\"tab-btn active\" data-tab=\"steps\">Steps</button>")
	b.WriteString("<button class=\"tab-btn\" data-tab=\"logs\">Logs</button>")
	b.WriteString("<button class=\"tab-btn\" data-tab=\"artifacts\">Artifacts</button>")
	b.WriteString("<button class=\"tab-btn\" data-tab=\"json\">Raw JSON</button>")
	b.WriteString("</div>")
	b.WriteString("<div class=\"tab-content active\" id=\"tab-steps\"><div class=\"step-timeline\" id=\"step-timeline\"><span class=\"muted\">Loading steps...</span></div></div>")
	b.WriteString("<div class=\"tab-content\" id=\"tab-logs\"><div class=\"log-console\" id=\"log-console\"><div class=\"log-line\"><span class=\"log-msg muted\">Loading logs...</span></div></div></div>")
	b.WriteString("<div class=\"tab-content\" id=\"tab-artifacts\"><div class=\"artifact-list\" id=\"artifact-list\"><span class=\"muted\">Loading artifacts...</span></div></div>")
	b.WriteString("<div class=\"tab-content\" id=\"tab-json\"><pre id=\"run-json\">Loading...</pre></div>")
	b.WriteString("</div>")
	b.WriteString("<script>")
	b.WriteString("const card=document.querySelector('[data-run-id]');")
	b.WriteString("const runId=card?card.dataset.runId:'';")
	b.WriteString("const statusEl=document.getElementById('run-status');")
	b.WriteString("const timingEl=document.getElementById('run-timing');")
	b.WriteString("const stepsEl=document.getElementById('run-steps');")
	b.WriteString("const artifactsEl=document.getElementById('run-artifacts');")
	b.WriteString("const logsEl=document.getElementById('run-logs');")
	b.WriteString("const toolsEl=document.getElementById('run-tools');")
	b.WriteString("const jsonEl=document.getElementById('run-json');")
	b.WriteString("const stepTimeline=document.getElementById('step-timeline');")
	b.WriteString("const logConsole=document.getElementById('log-console');")
	b.WriteString("const artifactList=document.getElementById('artifact-list');")
	b.WriteString("const countOf=(v)=>Array.isArray(v)?v.length:0;")
	// Tab switching
	b.WriteString("document.querySelectorAll('.tab-btn').forEach(btn=>{btn.addEventListener('click',()=>{")
	b.WriteString("document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));")
	b.WriteString("document.querySelectorAll('.tab-content').forEach(c=>c.classList.remove('active'));")
	b.WriteString("btn.classList.add('active');document.getElementById('tab-'+btn.dataset.tab).classList.add('active');});});")
	// Render steps
	b.WriteString("function renderSteps(steps){stepTimeline.innerHTML='';if(!steps||!steps.length){stepTimeline.innerHTML='<span class=\"muted\">No steps recorded</span>';return;}")
	b.WriteString("steps.forEach((s,i)=>{const div=document.createElement('div');")
	b.WriteString("const st=(s.status||'pending').toLowerCase();div.className='step-item s-'+st;")
	b.WriteString("const name=s.name||s.type||'Step '+(i+1);")
	b.WriteString("const ts=s.started_at?new Date(s.started_at).toLocaleTimeString():'';")
	b.WriteString("const dur=s.started_at&&s.completed_at?((new Date(s.completed_at)-new Date(s.started_at))/1000).toFixed(1)+'s':'';")
	b.WriteString("div.innerHTML='<div class=\"step-info\"><div class=\"step-name\">'+escapeHtml(name)+'</div><div class=\"step-meta\">'+escapeHtml(st)+' &middot; '+escapeHtml(ts)+'</div></div><div class=\"step-dur\">'+escapeHtml(dur)+'</div>';")
	b.WriteString("stepTimeline.appendChild(div);});}")
	// Render logs
	b.WriteString("function renderLogs(logs){logConsole.innerHTML='';if(!logs||!logs.length){logConsole.innerHTML='<div class=\"log-line\"><span class=\"log-msg muted\">No logs</span></div>';return;}")
	b.WriteString("logs.forEach(log=>{const div=document.createElement('div');div.className='log-line';")
	b.WriteString("const ts=log.timestamp?new Date(log.timestamp).toLocaleTimeString():'';")
	b.WriteString("const lvl=(log.level||'info').toLowerCase();")
	b.WriteString("div.innerHTML='<span class=\"log-ts\">'+escapeHtml(ts)+'</span><span class=\"log-lvl l-'+lvl+'\">'+escapeHtml(lvl)+'</span><span class=\"log-msg\">'+escapeHtml(log.message||log.content||JSON.stringify(log))+'</span>';")
	b.WriteString("logConsole.appendChild(div);});logConsole.scrollTop=logConsole.scrollHeight;}")
	// Render artifacts
	b.WriteString("function renderArtifacts(artifacts){artifactList.innerHTML='';if(!artifacts||!artifacts.length){artifactList.innerHTML='<span class=\"muted\">No artifacts</span>';return;}")
	b.WriteString("artifacts.forEach(a=>{const div=document.createElement('div');div.className='artifact-card';")
	b.WriteString("const name=a.name||a.path||a.id||'Artifact';const mime=a.mime_type||a.content_type||'';")
	b.WriteString("const size=a.size?((a.size/1024).toFixed(1)+' KB'):'';")
	b.WriteString("div.innerHTML='<div class=\"art-name\">'+escapeHtml(name)+'</div><div class=\"art-meta\">'+escapeHtml(mime+(size?' &middot; '+size:''))+'</div>'")
	b.WriteString("+(a.id?'<a class=\"art-link\" href=\"/api/v2/artifacts/'+encodeURIComponent(a.id)+'/content\" target=\"_blank\">Download</a>':'');")
	b.WriteString("artifactList.appendChild(div);});}")
	// Load run
	b.WriteString("async function loadRun(){statusEl.textContent='Loading...';")
	b.WriteString("try{const res=await fetch('/api/v2/runs/'+encodeURIComponent(runId));")
	b.WriteString("if(!res.ok)throw new Error('http '+res.status);")
	b.WriteString("const data=await res.json();const run=data&&data.run?data.run:data;")
	b.WriteString("const status=(run&&run.status?run.status:'UNKNOWN').toUpperCase();")
	b.WriteString("statusEl.textContent=status;statusEl.className='pill s-'+status;")
	b.WriteString("stepsEl.textContent=countOf(run&&run.steps);")
	b.WriteString("artifactsEl.textContent=countOf(run&&run.artifacts);logsEl.textContent=countOf(run&&run.logs);")
	b.WriteString("toolsEl.textContent=countOf(run&&run.tool_invocations);")
	b.WriteString("if(run&&run.started_at){let t='Started: '+new Date(run.started_at).toLocaleString();if(run.completed_at)t+=' | Ended: '+new Date(run.completed_at).toLocaleString();timingEl.textContent=t;}")
	b.WriteString("renderSteps(run&&run.steps);renderLogs(run&&run.logs);renderArtifacts(run&&run.artifacts);")
	b.WriteString("jsonEl.textContent=JSON.stringify(run,null,2);")
	b.WriteString("}catch(err){statusEl.textContent='Failed to load run';")
	b.WriteString("jsonEl.textContent=String(err&&err.message?err.message:err);}")
	b.WriteString("}")
	b.WriteString("loadRun();setInterval(loadRun,10000);")
	b.WriteString("</script>")
	b.WriteString(subPageFoot())
	return b.String()
}


func runsPlaceholderHandler(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path == "/runs" {
		r.URL.Path = "/runs/"
	}
	trimmed := strings.TrimPrefix(r.URL.Path, "/runs/")
	if trimmed == "" || trimmed == "/" {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		var b strings.Builder
		b.WriteString(subPageHead("Runs"))
		b.WriteString("<style>")
		b.WriteString("label{font-size:12px;color:#b0b0b0;margin-bottom:6px;display:block;}")
		b.WriteString(".row{display:flex;flex-wrap:wrap;gap:10px;align-items:center;}")
		b.WriteString("input{flex:1;min-width:220px;}")
		b.WriteString(".link{font-size:12px;color:#0078d4;text-decoration:none;border:1px dashed #505050;padding:8px 12px;border-radius:4px;}")
		b.WriteString(".link.disabled{color:#858585;border-color:#3c3c3c;pointer-events:none;}")
		b.WriteString(".runs-table{width:100%;border-collapse:collapse;margin-top:16px;font-size:12px;}")
		b.WriteString(".runs-table th{text-align:left;color:#858585;font-weight:500;padding:6px 10px;border-bottom:1px solid #505050;}")
		b.WriteString(".runs-table td{padding:6px 10px;border-bottom:1px solid #3c3c3c;color:#ccc;}")
		b.WriteString(".runs-table tr:hover td{background:#2a2a2a;}")
		b.WriteString(".status-badge{display:inline-block;padding:2px 8px;border-radius:3px;font-size:11px;font-weight:500;}")
		b.WriteString(".status-running{background:#1a3a1a;color:#4ec94e;}")
		b.WriteString(".status-succeeded{background:#1a331a;color:#73c991;}")
		b.WriteString(".status-failed{background:#3a1a1a;color:#f48771;}")
		b.WriteString(".status-cancelled{background:#3a3a1a;color:#cca700;}")
		b.WriteString(".empty{color:#858585;padding:20px 0;text-align:center;}")
		b.WriteString("</style>")
		b.WriteString("<div class=\"card\">")
		b.WriteString("<h1>Runs</h1>")
		b.WriteString("<p>Look up a run by ID or browse recent activity below.</p>")
		b.WriteString("<form id=\"run-lookup\" autocomplete=\"off\">")
		b.WriteString("<label for=\"run-id\">Run ID</label>")
		b.WriteString("<div class=\"row\">")
		b.WriteString("<input class=\"input\" id=\"run-id\" name=\"runId\" placeholder=\"run_abc123\" required>")
		b.WriteString("<button class=\"btn\" type=\"submit\">Open run</button>")
		b.WriteString("<a class=\"link disabled\" id=\"run-link\" href=\"/runs\">Open /runs/{runId}</a>")
		b.WriteString("</div>")
		b.WriteString("</form>")
		b.WriteString("</div>")
		b.WriteString("<div class=\"card\" style=\"margin-top:12px;\">")
		b.WriteString("<h2 style=\"margin-bottom:8px;\">Recent Runs</h2>")
		b.WriteString("<div style=\"display:flex;gap:8px;margin-bottom:8px;align-items:center;\">")
		b.WriteString("<button class=\"btn\" id=\"prev-btn\" disabled>← Previous</button>")
		b.WriteString("<span class=\"muted\" id=\"page-info\" style=\"font-size:12px;\"></span>")
		b.WriteString("<button class=\"btn\" id=\"next-btn\" disabled>Next →</button>")
		b.WriteString("</div>")
		b.WriteString("<div id=\"runs-list\"><p class=\"empty\">Loading...</p></div>")
		b.WriteString("</div>")
		b.WriteString("<script>")
		b.WriteString("const form=document.getElementById('run-lookup');")
		b.WriteString("const input=document.getElementById('run-id');")
		b.WriteString("const link=document.getElementById('run-link');")
		b.WriteString("function updateLink(){const value=input.value.trim();")
		b.WriteString("if(value){const href='/runs/'+encodeURIComponent(value);")
		b.WriteString("link.href=href;link.textContent='Open '+href;link.classList.remove('disabled');}")
		b.WriteString("else{link.href='/runs';link.textContent='Open /runs/{runId}';link.classList.add('disabled');}}")
		b.WriteString("form.addEventListener('submit',(e)=>{e.preventDefault();")
		b.WriteString("const value=input.value.trim();if(!value){input.focus();return;}")
		b.WriteString("window.location.href='/runs/'+encodeURIComponent(value);});")
		b.WriteString("input.addEventListener('input',updateLink);updateLink();")
		// Recent runs loader with pagination
		b.WriteString("const PAGE_SIZE=50;let currentOffset=0;")
		b.WriteString("const prevBtn=document.getElementById('prev-btn');")
		b.WriteString("const nextBtn=document.getElementById('next-btn');")
		b.WriteString("const pageInfo=document.getElementById('page-info');")
		b.WriteString("async function loadRuns(){const el=document.getElementById('runs-list');")
		b.WriteString("try{const resp=await fetch('/api/v2/runs?limit='+PAGE_SIZE+'&offset='+currentOffset);")
		b.WriteString("if(!resp.ok){el.innerHTML='<p class=\"empty\">Failed to load runs ('+resp.status+')</p>';return;}")
		b.WriteString("const data=await resp.json();const runs=data.runs||data||[];")
		b.WriteString("prevBtn.disabled=currentOffset===0;")
		b.WriteString("nextBtn.disabled=runs.length<PAGE_SIZE;")
		b.WriteString("pageInfo.textContent='Showing '+(currentOffset+1)+'-'+(currentOffset+runs.length);")
		b.WriteString("if(!runs.length&&currentOffset===0){el.innerHTML='<p class=\"empty\">No runs yet.</p>';pageInfo.textContent='';return;}")
		b.WriteString("if(!runs.length){currentOffset=Math.max(0,currentOffset-PAGE_SIZE);loadRuns();return;}")
		b.WriteString("if(!runs.length){el.innerHTML='<p class=\"empty\">No runs yet.</p>';return;}")
		b.WriteString("let html='<table class=\"runs-table\"><thead><tr><th>Run ID</th><th>Task</th><th>Agent</th><th>Status</th><th>Started</th></tr></thead><tbody>';")
		b.WriteString("runs.forEach(r=>{const sc=r.status||'unknown';")
		b.WriteString("const statusMap={'RUNNING':'running','SUCCEEDED':'succeeded','FAILED':'failed','CANCELLED':'cancelled'};const cls=statusMap[sc]||'cancelled';")
		b.WriteString("const started=r.started_at?new Date(r.started_at).toLocaleString():'—';")
		b.WriteString("html+='<tr><td><a href=\"/runs/'+encodeURIComponent(r.id)+'\" style=\"color:#0078d4;\">'+r.id+'</a></td>';")
		b.WriteString("html+='<td>#'+(r.task_id||'—')+'</td>';")
		b.WriteString("html+='<td>'+(r.agent_id||'—')+'</td>';")
		b.WriteString("html+='<td><span class=\"status-badge status-'+cls+'\">'+sc+'</span></td>';")
		b.WriteString("html+='<td>'+started+'</td></tr>';});")
		b.WriteString("html+='</tbody></table>';el.innerHTML=html;}")
		b.WriteString("catch(err){el.innerHTML='<p class=\"empty\">Error: '+err+'</p>';}}")
		b.WriteString("loadRuns();")
		b.WriteString("prevBtn.addEventListener('click',()=>{currentOffset=Math.max(0,currentOffset-PAGE_SIZE);loadRuns();});")
		b.WriteString("nextBtn.addEventListener('click',()=>{currentOffset+=PAGE_SIZE;loadRuns();});")
		b.WriteString("</script>")
		b.WriteString(subPageFoot())
		fmt.Fprint(w, b.String())
		return
	}
	if strings.Contains(trimmed, "/") {
		http.NotFound(w, r)
		return
	}
	page := runViewerPage(trimmed)
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	fmt.Fprint(w, page)
}

