package server

import (
"fmt"
"html"
"net/http"
"strings"
)


func contextPackDetailPage(packID string) string {
	var b strings.Builder
	b.WriteString(subPageHead("Context Pack"))
	b.WriteString("<style>")
	b.WriteString("ul{list-style:none;padding:0;margin:0;display:grid;gap:6px;font-size:12px;}")
	b.WriteString("li{background:#1e1e1e;border:1px solid #3c3c3c;border-radius:4px;padding:6px 8px;}")
	b.WriteString(".panel{background:#1e1e1e;border:1px solid #3c3c3c;border-radius:8px;padding:12px;}")
	b.WriteString(".panel span{display:block;font-size:11px;color:#858585;margin-bottom:6px;}")
	b.WriteString(".summary{font-size:13px;color:#ccc;}")
	b.WriteString("</style>")
	b.WriteString("<div class=\"card\" data-pack-id=\"")
	b.WriteString(html.EscapeString(packID))
	b.WriteString("\">")
	b.WriteString("<h1>Context Pack</h1>")
	b.WriteString("<p>Pack ID: ")
	b.WriteString(html.EscapeString(packID))
	b.WriteString("</p>")
	b.WriteString("<div class=\"meta\">")
	b.WriteString("<span class=\"pill\" id=\"pack-status\">Loading...</span>")
	b.WriteString("<span class=\"muted\">/api/v2/context-packs/")
	b.WriteString(html.EscapeString(packID))
	b.WriteString("</span>")
	b.WriteString("</div>")
	b.WriteString("<div class=\"grid\">")
	b.WriteString("<div class=\"panel\"><span>Summary</span><div id=\"pack-summary\" class=\"summary\">-</div></div>")
	b.WriteString("<div class=\"panel\"><span>Files</span><ul id=\"pack-files\"></ul></div>")
	b.WriteString("</div>")
	b.WriteString("<pre id=\"pack-json\">Loading...</pre>")
	b.WriteString("</div>")
	b.WriteString("<script>")
	b.WriteString("const card=document.querySelector('[data-pack-id]');")
	b.WriteString("const packId=card?card.dataset.packId:'';")
	b.WriteString("const statusEl=document.getElementById('pack-status');")
	b.WriteString("const summaryEl=document.getElementById('pack-summary');")
	b.WriteString("const filesEl=document.getElementById('pack-files');")
	b.WriteString("const jsonEl=document.getElementById('pack-json');")
	b.WriteString("function setFiles(files){filesEl.innerHTML='';")
	b.WriteString("if(!files.length){const li=document.createElement('li');li.className='muted';li.textContent='No files';filesEl.appendChild(li);return;}")
	b.WriteString("files.forEach((file)=>{const li=document.createElement('li');")
	b.WriteString("const path=file&&file.path?file.path:'(unknown path)';")
	b.WriteString("const snippets=Array.isArray(file&&file.snippets)?file.snippets.length:0;")
	b.WriteString("li.textContent=snippets>0?path+' ('+snippets+' snippets)':path;filesEl.appendChild(li);});}")
	b.WriteString("async function loadPack(){statusEl.textContent='Loading...';")
	b.WriteString("summaryEl.textContent='-';jsonEl.textContent='Loading...';")
	b.WriteString("try{const res=await fetch('/api/v2/context-packs/'+encodeURIComponent(packId));")
	b.WriteString("if(!res.ok)throw new Error('http '+res.status);")
	b.WriteString("const data=await res.json();const pack=data&&data.context_pack?data.context_pack:data;")
	b.WriteString("statusEl.textContent='Loaded';")
	b.WriteString("summaryEl.textContent=pack&&pack.summary?pack.summary:'No summary';")
	b.WriteString("const contents=pack&&pack.contents?pack.contents:{};")
	b.WriteString("let files=Array.isArray(contents.files)?contents.files:[];")
	b.WriteString("if(!files.length&&contents.repo_files&&Array.isArray(contents.repo_files.files)){files=contents.repo_files.files;}")
	b.WriteString("setFiles(files);")
	b.WriteString("jsonEl.textContent=JSON.stringify(pack,null,2);")
	b.WriteString("}catch(err){statusEl.textContent='Failed to load pack';")
	b.WriteString("summaryEl.textContent='-';filesEl.innerHTML='';")
	b.WriteString("const li=document.createElement('li');li.className='muted';")
	b.WriteString("li.textContent='Error loading files';filesEl.appendChild(li);")
	b.WriteString("jsonEl.textContent=String(err&&err.message?err.message:err);}")
	b.WriteString("}")
	b.WriteString("loadPack();")
	b.WriteString("</script>")
	b.WriteString(subPageFoot())
	return b.String()
}


func contextPacksPlaceholderHandler(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path == "/context-packs" {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		fmt.Fprint(w, contextPacksCreatePage())
		return
	}
	trimmed := strings.TrimPrefix(r.URL.Path, "/context-packs/")
	if trimmed == "" || trimmed == "/" {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		fmt.Fprint(w, contextPacksCreatePage())
		return
	}
	if strings.Contains(trimmed, "/") {
		http.NotFound(w, r)
		return
	}
	page := contextPackDetailPage(trimmed)
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	fmt.Fprint(w, page)
}

func contextPacksCreatePage() string {
	var b strings.Builder
	b.WriteString(subPageHead("Context Packs"))
	b.WriteString("<style>")
	b.WriteString("label{font-size:12px;color:#858585;margin-bottom:6px;display:block;}")
	b.WriteString(".row{display:flex;flex-wrap:wrap;gap:10px;align-items:center;}")
	b.WriteString(".meta{margin-top:8px;color:#858585;font-size:12px;}")
	b.WriteString(".status{margin-top:10px;color:#ccc;font-size:12px;}")
	b.WriteString("</style>")
	b.WriteString("<div class=\"card\">")
	b.WriteString("<h1>Context Packs</h1>")
	b.WriteString("<p>Create a minimal context pack for a task and view the JSON response.</p>")
	b.WriteString("<form id=\"context-pack-form\" autocomplete=\"off\">")
	b.WriteString("<label for=\"cp-project\">Project ID</label>")
	b.WriteString("<div class=\"row\">")
	b.WriteString("<input id=\"cp-project\" name=\"project\" value=\"proj_default\">")
	b.WriteString("<button class=\"btn\" type=\"button\" id=\"load-tasks-btn\" style=\"font-size:11px;\">Load Tasks</button>")
	b.WriteString("</div>")
	b.WriteString("<label for=\"task-id\">Task ID</label>")
	b.WriteString("<div class=\"row\">")
	b.WriteString("<select id=\"task-id\" name=\"taskId\" required><option value=\"\">-- select a task --</option></select>")
	b.WriteString("<input id=\"task-id-manual\" type=\"number\" min=\"1\" placeholder=\"or type ID\" style=\"width:90px;\">")
	b.WriteString("</div>")
	b.WriteString("<label for=\"query\">Query (optional)</label>")
	b.WriteString("<div class=\"row\">")
	b.WriteString("<input id=\"query\" name=\"query\" placeholder=\"focus on migrations\">")
	b.WriteString("<button class=\"btn\" type=\"submit\">Create pack</button>")
	b.WriteString("</div>")
	b.WriteString("</form>")
	b.WriteString("<div class=\"meta\" id=\"cp-endpoint\">POST /api/v2/projects/proj_default/context-packs</div>")
	b.WriteString("<div class=\"status\" id=\"context-pack-status\">Status: idle</div>")
	b.WriteString("<div id=\"cp-link\" style=\"display:none;margin-top:8px;\"></div>")
	b.WriteString("<pre id=\"context-pack-output\">{}</pre>")
	b.WriteString("</div>")
	b.WriteString("<script>")
	b.WriteString("const form=document.getElementById('context-pack-form');")
	b.WriteString("const taskSelect=document.getElementById('task-id');")
	b.WriteString("const taskManual=document.getElementById('task-id-manual');")
	b.WriteString("const queryInput=document.getElementById('query');")
	b.WriteString("const projectInput=document.getElementById('cp-project');")
	b.WriteString("const statusEl=document.getElementById('context-pack-status');")
	b.WriteString("const outputEl=document.getElementById('context-pack-output');")
	b.WriteString("const endpointEl=document.getElementById('cp-endpoint');")
	b.WriteString("const linkEl=document.getElementById('cp-link');")
	// Load tasks into dropdown
	b.WriteString("async function loadTasks(){const pid=String(projectInput.value||'proj_default').trim();")
	b.WriteString("try{const r=await fetch('/api/v2/projects/'+encodeURIComponent(pid)+'/tasks');")
	b.WriteString("if(!r.ok)return;const d=await r.json();const tasks=d.tasks||[];")
	b.WriteString("taskSelect.innerHTML='<option value=\"\">-- select a task --</option>';")
	b.WriteString("tasks.forEach(t=>{const o=document.createElement('option');o.value=t.id;")
	b.WriteString("o.textContent='#'+t.id+' '+((t.title||'').substring(0,60));taskSelect.appendChild(o);});")
	b.WriteString("}catch(e){console.error(e);}}")
	b.WriteString("document.getElementById('load-tasks-btn').addEventListener('click',loadTasks);")
	b.WriteString("loadTasks();")
	// Manual ID overrides dropdown
	b.WriteString("taskManual.addEventListener('input',()=>{if(taskManual.value){taskSelect.value='';}});")
	b.WriteString("taskSelect.addEventListener('change',()=>{if(taskSelect.value){taskManual.value='';}});")
	// Form submit
	b.WriteString("form.addEventListener('submit',async(e)=>{e.preventDefault();")
	b.WriteString("const taskId=taskManual.value.trim()||taskSelect.value;")
	b.WriteString("if(!taskId){statusEl.textContent='Status: select or enter a task ID';return;}")
	b.WriteString("const pid=String(projectInput.value||'proj_default').trim();")
	b.WriteString("endpointEl.textContent='POST /api/v2/projects/'+pid+'/context-packs';")
	b.WriteString("const payload={task_id:parseInt(taskId,10)};")
	b.WriteString("const query=queryInput.value.trim();")
	b.WriteString("if(query){payload.query=query;}")
	b.WriteString("statusEl.textContent='Status: sending...';outputEl.textContent='';linkEl.style.display='none';")
	b.WriteString("try{const resp=await fetch('/api/v2/projects/'+encodeURIComponent(pid)+'/context-packs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});")
	b.WriteString("const text=await resp.text();")
	b.WriteString("let data=text;try{data=JSON.parse(text);}catch(e){}")
	b.WriteString("outputEl.textContent=typeof data==='string'?data:JSON.stringify(data,null,2);")
	b.WriteString("statusEl.textContent='Status: '+resp.status;")
	// Show link to view pack on success
	b.WriteString("if(resp.ok&&typeof data==='object'){const pack=data.context_pack||data;")
	b.WriteString("if(pack&&pack.id){linkEl.innerHTML='<a href=\"/context-packs/'+encodeURIComponent(pack.id)+'\" style=\"color:#0078d4;\">View pack '+pack.id+'</a>';linkEl.style.display='block';}}")
	b.WriteString("}catch(err){statusEl.textContent='Status: error';outputEl.textContent=String(err);}});")
	b.WriteString("</script>")
	b.WriteString(subPageFoot())
	return b.String()
}

