/**
 * AUTO-GENERATED by tools/codegen/codegen.go -- DO NOT EDIT.
 * Generated at: 2026-03-08T06:17:45Z
 * Source files: models_v2.go, assignment.go
 */

export type TaskType =
  | "ANALYZE"
  | "MODIFY"
  | "TEST"
  | "REVIEW"
  | "DOC"
  | "RELEASE"
  | "ROLLBACK"
  | "PLAN";

export type RunStatus =
  | "RUNNING"
  | "SUCCEEDED"
  | "FAILED"
  | "CANCELLED";

export type StepStatus =
  | "STARTED"
  | "SUCCEEDED"
  | "FAILED";

export type AgentStatus =
  | "ONLINE"
  | "OFFLINE"
  | "BUSY"
  | "IDLE";

export interface Project {
  id: string;
  name: string;
  workdir: string;
  created_at: string;
}

export interface TreeNode {
  path: string;
  kind: string;
  size?: number;
  children?: TreeNode[];
}

export interface FileChange {
  path: string;
  kind: string;
  sha256?: string;
  ts: string;
}

export interface TaskV2 {
  id: number;
  project_id: string;
  title?: string;
  instructions: string;
  type: TaskType;
  priority: number;
  tags?: string[];
  status_v1: TaskStatus;
  status_v2: TaskStatusV2;
  parent_task_id?: number;
  output?: string;
  created_at: string;
  updated_at?: string;
  automation_depth: number;
  requires_approval?: boolean;
  approval_status?: string;
}

export interface TaskDependency {
  task_id: number;
  depends_on_task_id: number;
}

export interface Run {
  id: string;
  task_id: number;
  agent_id: string;
  status: RunStatus;
  started_at: string;
  finished_at?: string;
  error?: string;
}

export interface RunDetail {
  steps?: RunStep[];
  logs?: RunLog[];
  artifacts?: Artifact[];
  tool_invocations?: ToolInvocation[];
}

export interface RunStep {
  id: string;
  run_id: string;
  name: string;
  status: StepStatus;
  created_at: string;
}

export interface RunLog {
  id: number;
  run_id: string;
  stream: string;
  chunk: string;
  ts: string;
}

export interface Artifact {
  id: string;
  run_id: string;
  kind: string;
  storage_ref: string;
  sha256?: string;
  size?: number;
  created_at: string;
}

export interface ToolInvocation {
  id: string;
  run_id: string;
  tool_name: string;
  started_at: string;
  finished_at?: string;
}

export interface Lease {
  id: string;
  task_id: number;
  agent_id: string;
  mode: string;
  created_at: string;
  expires_at: string;
}

export interface Agent {
  id: string;
  name: string;
  capabilities?: string[];
  status: AgentStatus;
  last_seen?: string;
  registered_at: string;
}

export interface Event {
  id: string;
  project_id: string;
  kind: string;
  entity_type: string;
  entity_id: string;
  created_at: string;
}

export interface Memory {
  id: string;
  project_id: string;
  scope: string;
  key: string;
  source_refs?: string[];
  created_at: string;
  updated_at: string;
}

export interface Policy {
  id: string;
  project_id: string;
  name: string;
  description?: string;
  rules: PolicyRule[];
  enabled: boolean;
  created_at: string;
}

export interface ContextPack {
  id: string;
  project_id: string;
  task_id: number;
  summary: string;
  created_at: string;
  stale?: boolean;
}

export interface RunSummary {
  id: string;
  status: string;
  started_at: string;
  finished_at?: string;
  summary?: string;
  error_message?: string;
  files_touched?: string[];
}

export interface TaskTemplate {
  id: string;
  project_id: string;
  name: string;
  description?: string;
  instructions: string;
  default_type?: string;
  default_priority: number;
  default_tags?: string[];
  created_at: string;
  updated_at: string;
}

export interface RepoFile {
  id: string;
  project_id: string;
  path: string;
  content_hash?: string;
  size_bytes?: number;
  language?: string;
  last_modified?: string;
  created_at: string;
  updated_at: string;
}

export interface ArtifactComment {
  id: string;
  artifact_id: string;
  project_id?: string;
  line_number: number;
  body: string;
  author?: string;
  created_at: string;
  updated_at: string;
}

export interface DashboardData {
  project_id: string;
  task_counts: DashboardTaskCounts;
  active_runs: DashboardRun[];
  recent_changes: DashboardRepoChange[];
  recent_failures: DashboardFailure[];
  automation_events: DashboardAutoEvent[];
  recommendations: DashboardRecommendation[];
  stalled_tasks: DashboardStalledTask[];
}

export interface DashboardTaskCounts {
  queued: number;
  in_progress: number;
  completed: number;
  failed: number;
}

export interface DashboardRun {
  run_id: string;
  task_title: string;
  status: string;
  started_at: string;
}

export interface DashboardRepoChange {
  path: string;
  updated_at: string;
}

export interface DashboardFailure {
  task_id: number;
  title?: string;
  error?: string;
  updated_at: string;
}

export interface DashboardAutoEvent {
  kind: string;
  created_at: string;
}

export interface DashboardRecommendation {
  task_id: number;
  title?: string;
  priority: number;
  type?: string;
  why: string;
}

export interface DashboardStalledTask {
  task_id: number;
  title?: string;
  status: string;
  agent_id?: string;
  claimed_at: string;
  reason: string;
}

export interface CompletionContract {
  required_fields?: string[];
  expected_outputs?: string[];
  notes?: string;
}

export interface AssignmentEnvelope {
  task?: TaskV2;
  lease?: Lease;
  run?: Run;
  project?: Project;
  policy_snapshot?: Policy[];
  completion_contract?: CompletionContract;
  context?: TaskContext;
}

export interface ArtifactSummary {
  run_id: string;
  kind: string;
  storage_ref: string;
  size?: number;
}

export interface ContextQuality {
  score: number;
  category_counts: Record<string, unknown>;
  budget_used_bytes: number;
  budget_max_bytes: number;
}

export interface TaskContext {
  context_pack?: ContextPack;
  memories?: Memory[];
  policies?: Policy[];
  dependencies?: TaskDependency[];
  recent_run_summaries?: RunSummary[];
  repo_files?: string[];
  artifact_summaries?: ArtifactSummary[];
  quality?: ContextQuality;
}

